# PANDAS

In [2]:
import pandas as pd

1. Write a Python program to create and display a one-dimensional array-like object
containing an array of data using Pandas module.

In [3]:
new_1darray_series = pd.Series([num for num in range(10,35,5)],dtype=float)
print(new_1darray_series)
print(new_1darray_series.values)

0    10.0
1    15.0
2    20.0
3    25.0
4    30.0
dtype: float64
[10. 15. 20. 25. 30.]


2. Write a Python program to convert a Panda module Series to Python list and it's type.

In [4]:
new_1darray_series = pd.Series([num for num in range(10,35,2)],dtype=int)
print(new_1darray_series)
lst = new_1darray_series.tolist()
print(lst)

0     10
1     12
2     14
3     16
4     18
5     20
6     22
7     24
8     26
9     28
10    30
11    32
12    34
dtype: int64
[10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34]


3. Write a Python program to add, subtract, multiple and divide two Pandas Series. Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [5]:
d1 = pd.Series([2, 4, 6, 8, 10])
d2 = pd.Series([1, 3, 5, 7, 9])
print(f"Original Series:\n{d1.values}\n{d2.values} \nAddition: {(d1+d2).values}\nSubtraction: {(d1-d2).values}\nMultiplication: {(d1*d2).values}\nDivision: {(d1/d2).values}")

Original Series:
[ 2  4  6  8 10]
[1 3 5 7 9] 
Addition: [ 3  7 11 15 19]
Subtraction: [1 1 1 1 1]
Multiplication: [ 2 12 30 56 90]
Division: [2.         1.33333333 1.2        1.14285714 1.11111111]


4. Write a Python program to get the powers of an array values element-wise.
Note: First array elements raised to powers from second array
##### Expected Output:
Original array
- [0 1 2 3 4 5 6]
##### First array elements raised to powers from second array, element-wise:
- [ 0 1 8 27 64 125 216]

In [6]:
arr = pd.Series([0,1,2,3,4,5,6])
arr2 = pd.Series([0,1,3,3,3,3,3])
print(arr.values)
print(arr.values**arr2.values)

[0 1 2 3 4 5 6]
[  1   1   8  27  64 125 216]


5. Write a Python program to create and display a DataFrame from a specified dictionary
data which has the index labels.

In [7]:
import numpy as np
xam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(xam_data,index=labels)
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


6. Write a Python program to display a summary of the basic information about a
specified Data Frame and its data

In [8]:
print(df.info())
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      10 non-null     object 
 1   score     8 non-null      float64
 2   attempts  10 non-null     int64  
 3   qualify   10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes
None
           score   attempts
count   8.000000  10.000000
mean   13.562500   1.900000
std     4.693746   0.875595
min     8.000000   1.000000
25%     9.000000   1.000000
50%    13.500000   2.000000
75%    17.125000   2.750000
max    20.000000   3.000000


7. Write a Python program to get the first 3 rows of a given DataFrame.
Sample Python dictionary data and list labels:

In [9]:
df[:3]

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes

8. Write a Python program to select the 'name' and 'score' columns from the following
DataFrame

In [10]:
df[['name','score']]

name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0

9. Write a Python program to select the specified columns and rows from a given data
frame.
Select 'name' and 'score' columns in rows 1, 3, 5, 6 from the following data frame.

In [11]:
df.iloc[[1,3,5,6],[0,1]]

name  score
b     Dima    9.0
d    James    NaN
f  Michael   20.0
g  Matthew   14.5

10. Write a Python program to select the rows where the number of attempts in the
examination is greater than 2.

In [12]:
df[df.attempts>2]

name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

11. Write a Python program to count the number of rows and columns of a DataFrame.
Sample data:

In [13]:
print(len(df.index))
print(len(df.columns))
print(df.shape)
x,y = df.shape
print(x,y)

10
4
(10, 4)
10 4


12. Write a Python program to select the rows where the score is missing

In [14]:
print(df[df.score.isna()])
print(df[df.score.isnull()])
df[df.score.isna()]

    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no
    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no


name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no

13. Write a Python program to select the rows where number of attempts in the
examination is less than 2 and score greater than 15.

In [15]:
df[(df.attempts<2) & (df.score>15)]

name  score  attempts qualify
j  Jonas   19.0         1     yes

14. Write a Python program to change the score in row 'd' to 11.5

In [16]:
print(df)
df.loc['d','score'] = 11.5
df

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

15. Write a Python program to calculate the sum of the examination attempts by the
students.

In [17]:
import numpy as np
xam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(xam_data,index=labels)
print(df)
print(f'sum of exam attempts: {sum(df.attempts)}')

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
sum of exam attempts: 19


16. Write a Python program to calculate the mean score for each different student in
DataFrame.

In [18]:
print(f'mean score of all students: {df.score.mean()}')

mean score of all students: 13.5625


17. Write a Python program to append a new row 'k' to data frame with given values for
each column. Now delete the new row and return the original DataFrame

In [19]:
df.loc['k'] = ['Suresh',15.5,1,'yes']
print(df)
df.drop('k')

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
k     Suresh   15.5         1     yes


name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

18. Write a Python program to sort the DataFrame first by 'name' in descending order,
then by 'score' in ascending order

In [20]:
df.sort_values(by='name', ascending=False)

name  score  attempts qualify
k     Suresh   15.5         1     yes
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
c  Katherine   16.5         2     yes
j      Jonas   19.0         1     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
b       Dima    9.0         3      no
a  Anastasia   12.5         1     yes

In [21]:
df.sort_values(by='score')

name  score  attempts qualify
i      Kevin    8.0         2      no
b       Dima    9.0         3      no
e      Emily    9.0         2      no
a  Anastasia   12.5         1     yes
g    Matthew   14.5         1     yes
k     Suresh   15.5         1     yes
c  Katherine   16.5         2     yes
j      Jonas   19.0         1     yes
f    Michael   20.0         3     yes
d      James    NaN         3      no
h      Laura    NaN         1      no

20. Write a Python program to delete the 'attempts' column from the DataFrame.

In [22]:
df.drop('attempts', axis=1)

name  score qualify
a  Anastasia   12.5     yes
b       Dima    9.0      no
c  Katherine   16.5     yes
d      James    NaN      no
e      Emily    9.0      no
f    Michael   20.0     yes
g    Matthew   14.5     yes
h      Laura    NaN      no
i      Kevin    8.0      no
j      Jonas   19.0     yes
k     Suresh   15.5     yes

21. Write a Python program to insert a new column in existing DataFrame.

In [23]:
import pandas as pd
import numpy as np

exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
             'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
             'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data, index=labels)

# Insert new column 'age' with values
df['age'] = [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
print(df)

        name  score  attempts qualify  age
a  Anastasia   12.5         1     yes   21
b       Dima    9.0         3      no   22
c  Katherine   16.5         2     yes   23
d      James    NaN         3      no   24
e      Emily    9.0         2      no   25
f    Michael   20.0         3     yes   26
g    Matthew   14.5         1     yes   27
h      Laura    NaN         1      no   28
i      Kevin    8.0         2      no   29
j      Jonas   19.0         1     yes   30


22. Write a Python program to iterate over rows in a DataFrame.

In [24]:
for index, row in df.iterrows():
    print(index, row['name'], row['score'])

a Anastasia 12.5
b Dima 9.0
c Katherine 16.5
d James nan
e Emily 9.0
f Michael 20.0
g Matthew 14.5
h Laura nan
i Kevin 8.0
j Jonas 19.0


23. Write a Python program to get list from DataFrame column headers.
Sample data:

In [25]:
column_headers = list(df.columns)
print(column_headers)

['name', 'score', 'attempts', 'qualify', 'age']
